version: '3'

services:
  streaming:
    image: postgres
    ports:
      - '5432:5432'
    container_name: back-api
    restart: always
    volumes:
      - back-api-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_DB: back-api

volumes:
  back-disk: